import localFont from 'next/font/local'
import './globals.css'
import { SidebarProvider, SidebarTrigger } from '../components/ui/sidebar'
import { AppSidebar } from './components/AppSidebar'
import Calendar from './components/Calender'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900'
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function DashboardLayout ({ children }) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100`}
      >
        <SidebarProvider>
          <div className='flex w-full min-h-screen'>
            <AppSidebar />
            <main className='flex w-full gap-4 p-6'>
              <SidebarTrigger className='absolute z-50 top-4 md:hidden' />
              {children}
              <Calendar />
            </main>
          </div>
        </SidebarProvider>
      </body>
    </html>
  )
}
